# Generated by Django 4.1 on 2022-11-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
